apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: spring-boot-pom
    http:
      url: https://raw.githubusercontent.com/spring-projects/spring-boot/v3.3.0/pom.xml
